"""
visualize_sensitivity.py

Plots the parameter sensitivity analysis produced by sensitivity_analysis.py.

It reads the CSVs from the most recent output/sensitivity_<timestamp>/ run,
extracts the parameter values from the file names, and — for the extension
sweep (gap_extension_cost varied, gap_power fixed) — emits one TikZ figure
per log with two panels side by side:

    left  panel: median Alignment Cost  vs. gap_extension_cost
    right panel: median Fitness          vs. gap_extension_cost

Each panel has one line per cost model. Linear does not depend on the gap
parameters and appears as a flat reference line.

The power sweep (gap_power varied, only affects the Power model) is reported
as a console table so it can be discussed in the text; it is not mixed into
the same x-axis because it is a different parameter.
"""

import math
import re
from collections import defaultdict
from pathlib import Path

from visualize_results import (
    OUTPUT_DIR, DATA_DIR,
    COST_MODEL_KEYS, MODEL_COLORS,
    compute_best_worst_cost, load_result_csv, weighted_boxplot_stats,
    _fmt,
)

TIKZ_OUT_DIR   = Path("output/tikz")
THRESHOLD_TAG  = "pn50"   # the sensitivity run uses pn50

# Short TikZ colour names per model (pgfplots-friendly), derived from MODEL_COLORS.
MODEL_TIKZ_COLOR = {
    "Linear":        "myblue",
    "Affine":        "myorange",
    "Logarithmic":   "mygreen",
    "Power (d=0.7)": "myred",
}
MODEL_SHORT = {
    "Linear":        "Linear",
    "Affine":        "Affine",
    "Logarithmic":   "Logarithmic",
    "Power (d=0.7)": "Power",
}

FNAME_RE = re.compile(r"open([\d.]+)_ext([\d.]+)_d([\d.]+)")


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def latest_sensitivity_dir() -> Path | None:
    candidates = sorted(
        (p for p in OUTPUT_DIR.iterdir()
         if p.is_dir() and p.name.startswith("sensitivity_")),
        key=lambda p: p.name,
    )
    return candidates[-1] if candidates else None


def parse_params(csv_path: Path) -> tuple[float, float, float] | None:
    m = FNAME_RE.search(csv_path.name)
    if not m:
        return None
    return float(m.group(1)), float(m.group(2)), float(m.group(3))


# ---------------------------------------------------------------------------
# Median extraction
# ---------------------------------------------------------------------------

def weighted_median(df, column: str) -> float:
    stats = weighted_boxplot_stats(
        df[column].to_numpy(dtype=float),
        df["frequency"].to_numpy(dtype=int),
    )
    return stats["median"]


# ---------------------------------------------------------------------------
# TikZ emission
# ---------------------------------------------------------------------------

def _tikz_sensitivity(x_values: list[float],
                      xlabel: str,
                      medians: dict[str, dict[str, list[float]]],
                      out_path: Path,
                      models: list[str] | None = None,
                      values: list[str] | None = None) -> None:
    """
    x_values: sorted list of the swept parameter values (x-axis).
    xlabel:   axis label for that parameter.
    medians:  {"cost"|"fitness": {model: [median per x value]}}.
    models:   which cost models to draw (default: all). Pass a single model
              (e.g. the power sweep) to omit the now-pointless reference lines
              and the legend.
    values:   which panels to draw, subset/order of ["cost", "fitness"]
              (default: both). Pass one (e.g. ["fitness"]) for a single panel.
    """
    if models is None:
        models = COST_MODEL_KEYS
    if values is None:
        values = ["cost", "fitness"]
    single      = len(models) == 1
    ylabels     = {"cost": "median Alignment Cost", "fitness": "median Fitness"}
    n_panels    = len(values)
    color_defs = [
        "\\definecolor{myblue}{HTML}{1F77B4}",
        "\\definecolor{myorange}{HTML}{FF7F0E}",
        "\\definecolor{mygreen}{HTML}{2CA02C}",
        "\\definecolor{myred}{HTML}{D62728}",
    ]

    lines: list[str] = [
        "% Auto-generated by visualize_sensitivity.py — do not edit by hand.",
        "% Required in the LaTeX preamble:",
        "%   \\usepackage{pgfplots}",
        "%   \\pgfplotsset{compat=1.18}",
        "%   \\usepgfplotslibrary{groupplots}",
        "%   \\usetikzlibrary{calc}",
        *color_defs,
        "\\begin{tikzpicture}",
        "\\begin{groupplot}[",
        f"  group style={{group size={n_panels} by 1, horizontal sep=1.4cm}},",
        f"  width={'0.46' if n_panels > 1 else '0.6'}\\linewidth, height=5.5cm,",
        f"  xlabel={{{xlabel}}},",
        "  xtick={" + ",".join(_fmt(v) for v in x_values) + "},",
        "  label style={font=\\footnotesize},",
        "  tick label style={font=\\footnotesize},",
        "  title style={font=\\small},",
        "  legend to name=senslegend,",
        "  legend style={font=\\scriptsize, legend columns=4, /tikz/every even column/.append style={column sep=6pt}},",
        "  grid=major, major grid style={gray!20},",
        "]",
    ]

    for panel_idx, value in enumerate(values):
        opts = [f"ylabel={{{ylabels[value]}}}"]
        if value == "fitness":
            opts.append("ymin=0, ymax=1")
        lines.append(f"\\nextgroupplot[{', '.join(opts)}]")
        for model in models:
            color  = MODEL_TIKZ_COLOR[model]
            coords = " ".join(
                f"({_fmt(x)},{_fmt(y)})"
                for x, y in zip(x_values, medians[value][model])
            )
            lines.append(
                f"\\addplot[color={color}, mark=*, mark size=1.5pt, thick] "
                f"coordinates {{{coords}}};"
            )
        if panel_idx == n_panels - 1 and not single:
            legend = ", ".join(MODEL_SHORT[m] for m in models)
            lines.append(f"\\legend{{{legend}}}")

    lines.append("\\end{groupplot}")
    # Legend centred beneath the whole figure. Only multi-model figures have
    # one, and those always use the two-panel layout.
    if not single:
        lines.append(
            "\\node[anchor=north, yshift=-0.7cm] at "
            "($(group c1r1.south)!0.5!(group c2r1.south)$) "
            "{\\pgfplotslegendfromname{senslegend}};"
        )
    lines.append("\\end{tikzpicture}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Per-log processing
# ---------------------------------------------------------------------------

def process_log(log_dir: Path) -> None:
    log_name = log_dir.name
    print(f"\n[{log_name}]")

    pnml = DATA_DIR / f"{log_name}_{THRESHOLD_TAG}.pnml"
    if not pnml.exists():
        print(f"  ⚠  {pnml} missing — cannot compute fitness. Skipping.")
        return
    bwc = compute_best_worst_cost(pnml)

    # Group CSVs into extension sweep (d fixed = 0.7) and power sweep (ext = 0.5).
    ext_sweep: dict[float, Path] = {}
    pow_sweep: dict[float, Path] = {}
    for csv_path in log_dir.glob("*_gap_aware_align.csv"):
        params = parse_params(csv_path)
        if params is None:
            continue
        _open, ext, d = params
        if abs(d - 0.7) < 1e-9:
            ext_sweep[ext] = csv_path
        if abs(ext - 0.5) < 1e-9:
            pow_sweep[d] = csv_path

    if not ext_sweep:
        print("  No extension-sweep CSVs found — skipping.")
        return

    def collect_medians(sweep: dict[float, Path]):
        x_values = sorted(sweep)
        med: dict[str, dict[str, list[float]]] = {
            "cost": {m: [] for m in COST_MODEL_KEYS},
            "fitness": {m: [] for m in COST_MODEL_KEYS},
        }
        for x in x_values:
            df = load_result_csv(sweep[x], bwc)
            for model in COST_MODEL_KEYS:
                med["cost"][model].append(weighted_median(df, f"cost_{model}"))
                med["fitness"][model].append(weighted_median(df, f"fitness_{model}"))
        return x_values, med

    def print_table(title: str, x_label: str, x_values, med):
        print(f"\n  {title}")
        print(f"    {x_label:>6}", *[f"{MODEL_SHORT[m]:>12}" for m in COST_MODEL_KEYS])
        for i, x in enumerate(x_values):
            row = "  ".join(
                f"{med['cost'][m][i]:.3f}/{med['fitness'][m][i]:.3f}"
                for m in COST_MODEL_KEYS
            )
            print(f"    {x:>6}  {row}")

    # ---- Extension sweep (gap_extension_cost varied, d fixed) ----------
    ext_values, ext_med = collect_medians(ext_sweep)
    out = TIKZ_OUT_DIR / f"{log_name}_sensitivity_extension.tex"
    _tikz_sensitivity(ext_values, "gap extension cost", ext_med, out)
    print(f"  ✓  TikZ → {out}")
    print_table("Extension sweep (d=0.7) — median cost / fitness:", "ext",
                ext_values, ext_med)

    # ---- Power sweep (gap_power varied, ext fixed) --------------------
    # Only the Power model depends on d; the others appear as flat references.
    if len(pow_sweep) >= 2:
        pow_values, pow_med = collect_medians(pow_sweep)
        out = TIKZ_OUT_DIR / f"{log_name}_sensitivity_power.tex"
        _tikz_sensitivity(pow_values, "gap power $d$", pow_med, out,
                          models=["Power (d=0.7)"], values=["fitness"])
        print(f"  ✓  TikZ → {out}")
        print_table("Power sweep (ext=0.5) — median cost / fitness:", "d",
                    pow_values, pow_med)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sens_dir = latest_sensitivity_dir()
    if sens_dir is None:
        print("No output/sensitivity_* directory found. Run sensitivity_analysis.py first.")
    else:
        print(f"Using {sens_dir}")
        for log_dir in sorted(p for p in sens_dir.iterdir() if p.is_dir()):
            process_log(log_dir)
    print("\nDone.")
